version: '3'

vars:
  BINARY_NAME:
    sh: basename $(pwd)
  BUILD_DIR: 'build'
  OUTPUT_DIR: '{{.BUILD_DIR}}/{{.BINARY_NAME}}'
  COVERAGE_FILE: '{{.BUILD_DIR}}/coverage.out'
  GOOS: 'darwin'
  GOARCH: 'arm64'

tasks:
  tidy:
    desc: '依存関係の整理を行います'
    cmds:
      - go mod tidy

  build:
    desc: 'デバッグ用のビルドを行い、成果物を build/ ディレクトリに出力します'
    env:
      GOOS: '{{.GOOS}}'
      GOARCH: '{{.GOARCH}}'
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -gcflags="all=-N -l" -o {{.OUTPUT_DIR}}

  build-release:
    desc: 'リリース用のビルドを行い、成果物を build/ ディレクトリに出力します'
    env:
      GOOS: '{{.GOOS}}'
      GOARCH: '{{.GOARCH}}'
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -ldflags="-s -w" -o {{.OUTPUT_DIR}}

  run:
    desc: 'ビルド後、アプリケーションを実行します'
    deps: [build]
    cmds:
      - ./{{.OUTPUT_DIR}}

  test:
    desc: 'テストを実行し、カバレッジ情報を生成します'
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go test -race -v -coverprofile={{.COVERAGE_FILE}} ./...

  bench:
    desc: 'ベンチマークテストを実行します'
    cmds:
      - go test -bench=. -benchmem ./...

  cover:
    desc: 'テストを実行し、カバレッジ情報を表示します'
    deps: [test]
    cmds:
      - go tool cover -func={{.COVERAGE_FILE}}

  clean:
    desc: 'ビルド生成物とカバレッジファイルを削除します'
    cmds:
      - rm -rf {{.BUILD_DIR}}

  help:
    desc: '利用可能なタスクの一覧を表示します'
    cmds:
      - task --list
